#!/usr/bin/env bash

##################################################
# VIM
##################################################

ln -sF ~/.dotfiles/settings/vim ~/.vim
ln -sF ~/.dotfiles/settings/vim/vimrc ~/.vimrc

# https://github.com/VundleVim/Vundle.vim#quick-start
# vim +PluginInstall +qall
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim --noplugin -u ~/.vim/vundles.vim -N "+set hidden" "+syntax on" +BundleInstall +qall



##################################################
# Atom
##################################################

#install atom plugins
# apm install --packages-file ~/.dotfiles/installers/atomfile

#symlink settings
#ln -Fs ~/.dotfiles/settings/atom/config.cson ~/.atom/config.cson
#ln -Fs ~/.dotfiles/settings/atom/snippets.cson ~/.atom/snippets.cson
#ln -Fs ~/.dotfiles/settings/atom/keymap.cson ~/.atom/keymap.cson
#ln -Fs ~/.dotfiles/settings/atom/styles.less ~/.atom/styles.less
#ln -Fs ~/.dotfiles/settings/atom/init.coffee ~/.atom/init.coffee
#ln -Fs ~/.dotfiles/settings/atom/packages ~/.atom/packages
