#!/usr/bin/env zsh

cd $(dirname $0)

ln -sF ~/.dotfiles/settings/ruby/aprc ~/.aprc
ln -sF ~/.dotfiles/settings/ruby/gemrc ~/.gemrc
ln -sF ~/.dotfiles/settings/ruby/irbrc ~/.irbrc
ln -sF ~/.dotfiles/settings/ruby/pryrc ~/.pryrc
ln -sF ~/.dotfiles/settings/ruby/rdebugrc ~/.rdebugrc

# install gems
rbenv shims
bundle install
gem update --system
gem update
