# execution order zprofile > zshrc > zlogin
# Executes commands at login before zshrc.

export LANG="en_US.UTF-8"
export BROWSER="open"
export EDITOR="mvim -v"
export VISUAL="atom ."
export PAGER="less"

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Directories that cd searches.
 cdpath=(
   ~/Dropbox/github
   ~/Dropbox/Thermoacoustic_Brain_Decoder
   $cdpath
 )

# Directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS="-F -g -i -M -R -S -w -X -z-4"

# Set the Less input preprocessor.
# Try both 'lesspipe' and 'lesspipe.sh' as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
