# execution order zprofile > zshrc > zlogin
# shortcut to this dotfiles path is $ZSH
export ZSH=$HOME/.zsh
export PROJECTS=~/Dropbox/github/



# get environment variables from ~/.private
#if [[ -a ~/.private ]]
#then
#  source ~/.private
#fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


typeset -U config_files # create variable config_files
config_files=($ZSH/*.zsh)


# load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# load all zsh but path.zsh and completion.zsh files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
do
  source $file
done

autoload -U compinit
compinit

# load every completion.zsh
for file in ${(M)config_files:#*/completion.zsh}
do
  source $file
done

unset config_files
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
